language: node_js
node_js:
   "14.15.4"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master